.github/workflows/docs.yml
README.rst
doc/manual/source/examples/resampleexample.rst
doc/manual/source/index.rst

Change readme to include conda-forge instead of diffpy and pip instead of easy_install.

Change install sources

---

.github/workflows/docs.yml
.github/workflows/main.yml
README.rst
doc/manual/source/conf.py
pyproject.toml
src/diffpy/utils/version.py

Removed support for 3.8 (`importlib` not available).
Updated readme instructions.
Simple tag-based dynamic versioning (same as old `setup.py` versioning process).

Tag-based dynamic versioning

---

.flake8
.isort.cfg
.pre-commit-config.yaml
prevent_commit_to_main.sh

adding .flake8, .isort.cfg, .pre-commit-config.yaml, and prevent_commit_to_main.sh

Files for pre-commit

---

doc/manual/source/utilities/toolsutility.rst
src/diffpy/utils/version.py

Since we no longer use `setup.py`, we cannot run `egg_info`:
```
/home/sparkypenguin/.local/lib/python3.10/site-packages/diffpy/utils/version.py:39: UserWarning: Package metadata not found, execute "./setup.py egg_info".
warn('Package metadata not found, execute "./setup.py egg_info".')
```
This warning keeps arising when running items using utils. This PR fixes this issue by removing most of the (unused) `version.py` code as it takes the information from the generated `version.cfg` file.
Also some formatting fixes to `toolsutility.rst` (can be made into a separate PR if requested).

Fix version

---

.github/workflows/matrix-and-codecov-on-merge-to-main.yml

hopefully closes #106 
Something worth notice is that {{ secrets.GITHUB_TOKEN }} works differently than other secrets (e.g. {{ secrets.CODECOV_TOKEN }} such that GitHub_token doesn't need any extra configuration and is available for every workflow when it runs, while other secrets are needed to be passed to the reusable workflows.

add secrets inherit

---

requirements/test.txt

We shall use pytest-cov instead of using coverage to run pytest. The previous codecov 0% error occurred because the tests folder has been moved to the top directory level and coverage isn't able to import diffpy.<package-name> due to the namespace.
So the GH actions can be modified 
from:
```
run: |
coverage run -m pytest -vv -s
coverage report -m
codecov
```
to:
```
run: |
pytest --cov
coverage report -m
codecov
```
Reference:
- https://github.com/diffpy/diffpy.snmf/pull/86

Add pytest-cov test.txt dependency list

---

news/git-version.rst
pyproject.toml

Since `diffpy.utils`, is already cookiecuttered, manually fix this versioning.
Reference:
- https://github.com/Billingegroup/cookiecutter/pull/154

Update setuptools-git-versioning >= 2.0

---

.codespell/ignore_lines.txt
.codespell/ignore_words.txt
.pre-commit-config.yaml
CHANGELOG.rst
README.rst
news/codespell.rst
pyproject.toml
src/diffpy/utils/parsers/loaddata.py
src/diffpy/utils/parsers/resample.py
src/diffpy/utils/parsers/serialization.py

closes #144 
@sbillinge Ready for review, sorry for the mistake earlier

Configure automatic spelling check via codespell within pre-commit

---

.github/ISSUE_TEMPLATE/release_checklist.md

We will also ask Alison to try using this checklist for 3.5.1. release.

Update release_checklist.md - use fourigui 0.2.0 version

---

news/deprecate.rst
src/diffpy/utils/scattering_objects/diffraction_objects.py
tests/diffpy/utils/scattering_objects/test_diffraction_objects.py

It was a direct copy from `Diffraction_object` to `DiffractionObject` (no manual modification) except the deprecation warnings/docstrings.

Deprecate `Diffraction_object`, rename to `DiffractionObject` (new clean PR)

---

news/test-refactor.rst
src/diffpy/utils/parsers/loaddata.py
tests/diffpy/utils/parsers/test_loaddata.py

Closes https://github.com/diffpy/diffpy.utils/issues/161 - since we may deprecate `loadData` to `load_data` or so, spent 5-10 mins to refactor this code.

Use pytest for `test_loaddata.py`

---

doc/source/examples/diffractionobjectsexample.rst
doc/source/utilities/diffractionobjectsutility.rst
news/tth-q.rst
src/diffpy/utils/scattering_objects/diffraction_objects.py
tests/diffpy/utils/scattering_objects/test_diffraction_objects.py

closes #174 
@sbillinge ready for review!

q_to_tth & tth_to_q

---

news/constructor.rst
src/diffpy/utils/diffraction_objects.py
src/diffpy/utils/transforms.py
tests/test_diffraction_objects.py
tests/test_transforms.py

closes #185 
closes #181
closes #177
and basic data structure is a 2D array with everything in it

DiffractionObject can now be instantiated directly

---

news/scattering_obt.rst
news/setter-property.rst
requirements/test.txt
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/194

Use `@property` to prevent direct modification of `all_arrays`

---

news/d-q.rst
src/diffpy/utils/transforms.py
tests/test_transforms.py

d_to_q, q_to_d

---

news/d-tth.rst
src/diffpy/utils/transforms.py
tests/test_transforms.py

add d_to_tth, tth_to_d

---

.github/ISSUE_TEMPLATE/release_checklist.md

Add New release checklist BG standard including `python -m build` and `twine check dist/*`

---

news/deepcopy.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

Closes #201 - add `copy()` for `DiffracitonObject`

Add `copy()` method for `DiffractionObject`

---

news/config-UX.rst
src/diffpy/utils/tools.py

closes #156 
@sbillinge ready for review, new message points to where users can update manually and examples on the diffpy.utils link

More info on updating global config for users

---

news/scattering-obj-valid.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

Check valid x and y array lenghts and xtypes in `insert_scattering_quantity` 

---

news/mv-input-scattering-quan.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/212
Since we are doing a big API migration, didn't add `deprecation warnings` if that's okay.

Rename `input_scattering_quantity` to `input_data` in `DiffractionObject` init

---

src/diffpy/utils/transforms.py
tests/test_diffraction_objects.py
tests/test_transforms.py

Here, the goal is to discuss how to write good tests using `@pytest.mark.parametrize` and also test warning messages.

1) Capture no wavelength `UserWarning` for `test_q_to_thh` method 2) discuss passing variables to `@pytest.mark.parametrize`

---

news/scaleto.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

tests for scale_to

---

tests/conftest.py
tests/test_diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/229 - Refactor test_on_xtype() using @pytest.mark.parametrize and conftest.py

Refactor `test-on-xtype` test function 

---

news/resample-dep.rst
src/diffpy/utils/resampler.py

closes #139 
as per discussion in #180 and #207 warnings.warn passes pytest under python 3.13, 3.12, 3.11

add deprecation warning to resample function

---

doc/source/examples/resampleexample.rst
news/nsinterp.rst
src/diffpy/utils/resampler.py
tests/test_resample.py

Runs `wsinterp` as a subroutine. Documentation and tests added.
Should be a separate function as the inputs require an additional `qmin`, `qmax` and we should not overload `wsinterp`.
Closes #48.

Add function for Nyquist-Shannon grid interpolation

---

tests/conftest.py
tests/test_transforms.py

No manual modifications were made to any of the test values. I think this PR will solidify our group's pytest practices and may be used as a concrete example (if we all agree).

Refactor `test_transfor.py`: pass variables to pytest parametrize, use `conftest.py` for common error messages

---

doc/source/examples/toolsexample.rst
news/tools-doc-update.rst

updated tools example doc with better get_user_info example

---

doc/source/examples/diffraction_objects_example.rst
news/doccln.rst

@yucongalicechen @alisnwu please can you review and see if the instructions make sense after my hacks.  Also, please check that they build ok.

Simon tweaks to DO examples

---

doc/source/examples/diffraction_objects_example.rst

fixed some typos. @sbillinge ready for review

fix diffraction objects docs typos

---

news/pytest-warning.rst
src/diffpy/utils/transforms.py
tests/test_diffraction_objects.py

The goal of this PR is to demonstrate how to refactor a specific test function. 
- Use variable names that are concise, clear, yet does not lose info
- Correctly use `@pytest.mark.parametrize` to init objects
- Differentiate info vs warning messages for end-users

Refactor `test_scale_to` function - continue to establish good practices

---

news/pytest-warnings-others.rst
tests/test_transforms.py

Making smaller PRs since @sbillinge is on the road.

Remove 6 pytest warnings with capturing wavelength warnings

---

news/pytest-wavelength-warnings.rst
tests/test_diffraction_objects.py
tests/test_transforms.py

Done..
```
======= 100 passed, 9 warnings in 0.20s ==========
```
9 warnings left - all coming from `divide by zero` error. I will fix this once https://github.com/diffpy/diffpy.utils/pull/260 is merged.

Catch `wavelength=none` warnings in DiffractionObject

---

news/pytest-warning-divide-zero.rst
tests/test_diffraction_objects.py
tests/test_transforms.py

Closes #223 
This PR focused on catching warnings. In the following PRs, I will focus on checking test comments and refactoring into reusable components with `conftest.py`

Fix all remaining divide by zero pytest warnings

---

.codecov.yml
.github/ISSUE_TEMPLATE/release_checklist.md
.github/workflows/build-wheel-release-upload.yml
.github/workflows/check-news-item.yml
.pre-commit-config.yaml
news/prettier-pre-commit.rst

@sbillinge 
Do we want to automate linting for `.md` and `.yaml` files with the following addition to `.pre-commit-config.yaml`?
```
- repo: https://github.com/pre-commit/mirrors-prettier
rev: f12edd9c7be1c20cfa42420fd0e6df71e42b51ea # frozen: v4.0.0-alpha.8
hooks:
- id: prettier
additional_dependencies:
- "prettier@^3.2.4"
```
No manual edits have been made.

Apply `prettier` to pre-commit for automatic linting of `.md` `.yaml` files

---

doc/source/examples/tools_example.rst
news/userinfo.rst
src/diffpy/utils/tools.py
tests/conftest.py
tests/test_tools.py

closes #245 
replaces #253 
@yucongalicechen @bobleesj ready for review.  I will put the config-file creation workflow on another PR
Commented text will be reused (and removed from here) in a separate function for creating a missing global config file in a future PR.

refactor  to separate getting info and creating config files

---

news/class-docstring.rst
src/diffpy/utils/diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/240 - DiffractionObject docstring do over

Add class docstring for `DiffractionObject`

---

doc/source/examples/tools_example.rst
doc/source/utilities/tools_utility.rst
news/user_info_doc.rst
src/diffpy/utils/tools.py

add docs for `check_and_build_global_config()`

---

news/pytest-comment.rst
tests/test_diffraction_objects.py

Some battle-tested practices being adopted:
- Replace UC to C
- Add higher-level test function comment before starting "C"
- Use "x, y, z (provided), expect blah blah blah" format for consistency
cc' @yucongalicechen

Improve test comments under `@pytest.mark.parametrize` in `test_diffraction_objects.py`

---

news/pytest-reformat-transform.rst
tests/test_transforms.py

It's a great practice for me - cementing the practice. I really like the current test format.

Improve pytest parametrize comments for `test_transform.py`

---

news/test-func-format-compact.rst
tests/test_diffraction_objects.py
tests/test_transforms.py

Closes https://github.com/diffpy/diffpy.utils/issues/276 - use compact test comment

Use compact test comment style for each case under @pytest.mark.parametrize

---

news/uuid-rename.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/269

Rename `id` to `uuid` in DiffractionObject

---

news/get-index.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/279

Fix `get_array_index` returns `int` instead of `list` in DiffractionObject

---

news/valid-empty-do.rst
tests/test_diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/241

Add two test cases for init DiffractionObject with empty `xarray` and `yarray` values

---

news/scaleto-comments.rst
tests/test_diffraction_objects.py

closes #274 
@bobleesj do you wanna give it a read first to see if the comments make sense to you?

improve comments for `test_scale_to`

---

news/add-operations-tests.rst
src/diffpy/utils/diffraction_objects.py
tests/conftest.py
tests/test_diffraction_objects.py

Starting with `__add__` first, and will make separate PRs for subtraction, multiplication, division, etc. after review

Refactor `__add__` operation in `DiffractionObject` and add tests

---

news/op-mul-sub-div.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

Closes #187 - 
No docstrings made at the moment, but I will do in the next PR working on the issue https://github.com/diffpy/diffpy.utils/issues/239

feat: Support *, /, - operations between two DiffractionObjects or scalar 

---

news/muD_calculator.rst
requirements/conda.txt
requirements/pip.txt
src/diffpy/utils/tools.py
tests/test_tools.py

closes #281 
This is a direct copy and paste from labpdfproc
I added a new issue for docs in #291

feat: muD calculator

---

doc/source/examples/diffraction_objects_example.rst
news/scaleto-max.rst
src/diffpy/utils/diffraction_objects.py
tests/test_diffraction_objects.py

closes #287
@sbillinge reafy for review

add new features in `scale_to()` so user can run without an x-value

---

news/no-news.rst
src/diffpy/utils/diffraction_objects.py
tests/conftest.py
tests/test_diffraction_objects.py

Closes https://github.com/diffpy/diffpy.utils/issues/298 -

fix: compare values and shape of `xarray` values before applying operations between 2 DiffractionObjects

---

doc/source/examples/diffraction_objects_example.rst
news/docs-do.rst

docs: add examples for operations

---

doc/source/api/diffpy.utils.parsers.rst
doc/source/api/diffpy.utils.rst
doc/source/api/diffpy.utils.wx.rst
news/is-float.rst
src/diffpy/utils/parsers/loaddata.py
src/diffpy/utils/validators.py
tests/test_validators.py

refactor: separate `isfloat` into a new file within `validators.py` and rename to `is_number`

---

.github/workflows/build-wheel-release-upload.yml
news/set-github-admin.rst

Closes https://github.com/diffpy/diffpy.utils/issues/304

fix: Add `sbillinge` as the designated authorized user for release in  `build-wheel-release-upload.yml`

---

news/DO-docstring.rst
src/diffpy/utils/diffraction_objects.py

docs: add docstrings for on_d, on_q, on_tth, and dump

---

CHANGELOG.rst
news/changelog-3.6.0-line-break.rst

Now works 
Ready for review - @sbillinge could you please redeploy doc by workflow dispatch? 
https://github.com/diffpy/diffpy.utils/actions/workflows/publish-docs-on-release.yml
Let' see... we will have to run from `main` since 3.6.0 tag wouldn't have this commit ... but let's see if it displays the version correctly?

docs: remove extra line break in 3.6.0 changelog.rst

---

docs/source/examples/diffraction_objects_example.rst
docs/source/examples/parsers_example.rst
docs/source/examples/resample_example.rst
news/fix-docs-example.rst

Fix the examples as mentioned in #352 
Fix the documentation examples.
Please check the modified documentation.
example for `DiffractionObject.get_array_index`
Duplicate code block is removed
Markup is now rendered correctly

docs: fix the example of using `DiffractionObject.get_array_index` in the documentation

---

docs/source/examples/transforms_example.rst

Closes #352 
Remove a d value from the documentation that will raise `ValueError`.

docs: fix the `diffpy.utils.transforms.d_to_tth` example

---

news/headerfile.rst
tests/test_serialization.py

@sbillinge please check, thanks
Normalize paths before assert in `test_serialization/test_load_multiple` to prevent possible Windows short/long name mismatch.

Normalize paths before assert
